global:
  cloud: aws
  clusterName: cpms-qat
  deploymentEnvironment: qat
otelCollectorEndpoint: otel-collector.signoz-qat.me:4317
otelInsecure: true
presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  resourceDetection:
    detectors:
      - eks
      - system
  logsCollection:
    enabled: true
    whitelist:
      enabled: true
      signozLogs: false
      namespaces:
        - cp