FROM --platform=linux/amd64 flink:1.19.0
#添加运行jar包
ADD dos_realtime_coupon-0.1.1-SNAPSHOT.jar /opt/flink/dos_realtime_coupon-0.1.1-SNAPSHOT.jar
#添加依赖包
ADD aws-kinesisanalytics-runtime-1.2.0.jar /opt/flink/lib/

mongodb+srv://qatDOsDevUs3r:xauxpSmaTRmY4EUE@qat-stable-dos-backoffi-pri.0ltpc.mongodb.net/dosdb?retryWrites=true&w=majority&appName=qat-stable-DOS-backoffice
