apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink-dos-realtime-coupon
    type: flink-native-kubernetes
  name: flink-dos-realtime-coupon-rest-internet
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  namespace: flink
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: flink-dos-realtime-coupon
      uid: f559351f-5de6-4fab-8659-ac97c51a328d
spec:
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: rest
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: flink-dos-realtime-coupon
    component: jobmanager
    type: flink-native-kubernetes
  sessionAffinity: None
  type: LoadBalancer
