# ConfigMap for Flink configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-super-jackpot-chances-config
  namespace: flink
data:
  application_properties.json: |-
    [{"PropertyGroupId":"RealtimeCoupon",
    "PropertyMap":{
      "cp.pulsar.consumer.name": "dos-flink-bet-consume-chances",
      "cp.pulsar.destination.service.url": "pulsar://pulsar-proxy-dos.dos99.me:6650",
      "cp.pulsar.service.url":"pulsar://pulsar-proxy-dos.dos99.me:6650",
      "cp.pulsar.subscription.name":"dos-flink-bet-consume-chances",
      "dos.sink.pulsar.producer":"dos-cp-flink-super-jackpot-chance-producer",
      "is.cp.source":true,
      "keyby.parallelism":64,
      "sink.parallelism":1,
      "source.parallelism":1,
      "super.jackpot.chance.job.enabled":true,
      "window.parallelism":64}
    }]
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-super-jackpot-chances
  namespace: flink
  labels:
    deploy.artifact.io/kind: 'flink'
    deploy.artifact.io/name: 'flink-super-jackpot-chances'
spec:
  image: 545009824097.dkr.ecr.ap-southeast-1.amazonaws.com/flink:dos_super_jackpot-0.1.1
  imagePullPolicy: Always
  flinkVersion: v1_19
  flinkConfiguration:
    jobmanager.memory.process.size: "1g"
    kubernetes.jobmanager.memory.limit-factor: "1.5"
    kubernetes.jobmanager.cpu.amount: "1"
    kubernetes.jobmanager.cpu.limit-factor: "8"
    taskmanager.memory.process.size: "1g"
    kubernetes.taskmanager.memory.limit-factor: "1.33"
    kubernetes.taskmanager.cpu.amount: "1"
    kubernetes.taskmanager.cpu.limit-factor: "8"
    parallelism.default: "4"
    taskmanager.data.port: "12000"
    high-availability.storageDir: s3://flink-dos-qat-jobs/flink-super-jackpot-chances/ha
    jobmanager.archive.fs.dir: s3://flink-dos-qat-jobs/flink-super-jackpot-chances/completed-jobs
    historyserver.archive.fs.dir: s3://flink-dos-qat-jobs/flink-super-jackpot-chances/completed-jobs
    state.backend.type: hashmap
    state.checkpoints.dir: s3://flink-dos-qat-jobs/flink-super-jackpot-chances/checkpoint/
    state.savepoints.dir: s3://flink-dos-qat-jobs/flink-super-jackpot-chances/savepoint/

  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
  jobManager:
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: flink-super-jackpot-chances-jm
        namespace: flink
        labels:
          deploy.artifact.io/kind: 'flink'
          deploy.artifact.io/name: 'flink-super-jackpot-chances'
      spec:
        containers:
          # Do not change the main container name
          - name: flink-main-container
            ports:
              - name: rpc
                containerPort: 6123
              - name: blob
                containerPort: 6124
              - name: ui
                containerPort: 8081
              - name: metric
                containerPort: 9249
            env:
              - name: module
                value: 'flink-super-jackpot-chances'
              - name: ENV
                value: 'qat'
              - name: FLINK_VER
                value: '1.19.0'
            readinessProbe:
              httpGet:
                path: /
                port: 8081
              initialDelaySeconds: 30
            volumeMounts:
              - name: flink-super-jackpot-chances-config
                mountPath: /etc/flink
        volumes:
          - name: flink-super-jackpot-chances-config
            configMap:
              name: flink-super-jackpot-chances-config

  taskManager:
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: flink-super-jackpot-chances-tm
        namespace: flink
        labels:
          deploy.artifact.io/kind: 'flink'
          deploy.artifact.io/name: 'flink-super-jackpot-chances'
      spec:
        serviceAccountName: flink-super-jackpot-chances
        containers:
          - name: flink-main-container
            ports:
              - name: data
                containerPort: 6121
              - name: rpc
                containerPort: 6122
              - name: metric
                containerPort: 9249
            env:
              - name: module
                value: 'flink-super-jackpot-chances'
              - name: ENV
                value: 'qat'
              - name: FLINK_VER
                value: '1.19.0'
            volumeMounts:
              - name: flink-super-jackpot-chances-config
                mountPath: /etc/flink
        volumes:
          - name: flink-super-jackpot-chances-config
            configMap:
              name: flink-super-jackpot-chances-config

  job:
    jarURI: local:///opt/flink/dos_super_jackpot-0.1.1-SNAPSHOT.jar
    parallelism: 4
    allowNonRestoredState: False
    upgradeMode: 'savepoint'
    state: 'running'