receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  regex:
    name: multi_line_logs
    rules:
      - match: "^(?<timestamp>[^ ]+) (?<stream>stdout|stderr) (?<level>[F|E]) (?<time>\\d{2}:\\d{2}:\\d{2}) \\d+\\|(?<source>[^|]+)\\| (?<message>.*)"
        action: merge
        fields:
          - message

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [regex]
      exporters: [debug]
