apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: signoz-prod:clickhouse.altinity.com/ClickHouseInstallation:platform/signoz-prod-clickhouse
  creationTimestamp: "2024-10-16T06:26:48Z"
  generation: 1
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: signoz-prod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-prod-clickhouse
    clickhouse.altinity.com/cluster: cluster
    clickhouse.altinity.com/namespace: platform
    clickhouse.altinity.com/object-version: 9e6a716ca6d400bd83a31aa2df77dd3d418e64cd
    clickhouse.altinity.com/replica: "0"
    clickhouse.altinity.com/shard: "0"
    helm.sh/chart: clickhouse-24.1.6
  name: chi-signoz-prod-clickhouse-cluster-0-0
  namespace: platform
  ownerReferences:
  - apiVersion: clickhouse.altinity.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: ClickHouseInstallation
    name: signoz-prod-clickhouse
    uid: d3f9c5b8-48a7-4ff2-bb07-25534da9a291
  resourceVersion: "19000323"
  uid: 5a237425-620b-478a-9a94-fd15532f22de
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      clickhouse.altinity.com/app: chop
      clickhouse.altinity.com/chi: signoz-prod-clickhouse
      clickhouse.altinity.com/cluster: cluster
      clickhouse.altinity.com/namespace: platform
      clickhouse.altinity.com/replica: "0"
      clickhouse.altinity.com/shard: "0"
  serviceName: chi-signoz-prod-clickhouse-cluster-0-0
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: signoz-prod:clickhouse.altinity.com/ClickHouseInstallation:platform/signoz-prod-clickhouse
        signoz.io/path: /metrics
        signoz.io/port: "9363"
        signoz.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: clickhouse
        app.kubernetes.io/instance: signoz-prod
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: clickhouse
        app.kubernetes.io/version: 24.1.2
        clickhouse.altinity.com/app: chop
        clickhouse.altinity.com/chi: signoz-prod-clickhouse
        clickhouse.altinity.com/cluster: cluster
        clickhouse.altinity.com/namespace: platform
        clickhouse.altinity.com/ready: "yes"
        clickhouse.altinity.com/replica: "0"
        clickhouse.altinity.com/shard: "0"
        helm.sh/chart: clickhouse-24.1.6
      name: pod-template
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml
        image: docker.io/clickhouse/clickhouse-server:24.1.2-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: clickhouse
        ports:
        - containerPort: 8123
          name: http
          protocol: TCP
        - containerPort: 9000
          name: client
          protocol: TCP
        - containerPort: 9009
          name: interserver
          protocol: TCP
        - containerPort: 9000
          name: tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: data-volumeclaim-template
        - mountPath: /var/lib/clickhouse/user_scripts
          name: shared-binary-volume
        - mountPath: /etc/clickhouse-server/functions
          name: custom-functions-volume
        - mountPath: /etc/clickhouse-server/config.d/
          name: chi-signoz-prod-clickhouse-common-configd
        - mountPath: /etc/clickhouse-server/users.d/
          name: chi-signoz-prod-clickhouse-common-usersd
        - mountPath: /etc/clickhouse-server/conf.d/
          name: chi-signoz-prod-clickhouse-deploy-confd-cluster-0-0
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - chi-signoz-prod-clickhouse-cluster-0-0
        ip: 127.0.0.1
      initContainers:
      - command:
        - sh
        - -c
        - |
          set -x
          wget -O /tmp/histogramQuantile https://github.com/SigNoz/signoz/raw/develop/deploy/docker/clickhouse-setup/user_scripts/histogramQuantile
          mv /tmp/histogramQuantile  /var/lib/clickhouse/user_scripts/histogramQuantile
          chmod +x /var/lib/clickhouse/user_scripts/histogramQuantile
        image: docker.io/alpine:3.18.2
        imagePullPolicy: IfNotPresent
        name: signoz-prod-clickhouse-udf-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/clickhouse/user_scripts
          name: shared-binary-volume
      nodeSelector:
        kubernetes.io/hostname: ip-10-150-3-26.ap-southeast-1.compute.internal
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 101
        runAsUser: 101
      serviceAccount: signoz-prod-clickhouse
      serviceAccountName: signoz-prod-clickhouse
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: shared-binary-volume
      - configMap:
          defaultMode: 420
          name: signoz-prod-clickhouse-custom-functions
        name: custom-functions-volume
      - configMap:
          defaultMode: 420
          name: chi-signoz-prod-clickhouse-common-configd
        name: chi-signoz-prod-clickhouse-common-configd
      - configMap:
          defaultMode: 420
          name: chi-signoz-prod-clickhouse-common-usersd
        name: chi-signoz-prod-clickhouse-common-usersd
      - configMap:
          defaultMode: 420
          name: chi-signoz-prod-clickhouse-deploy-confd-cluster-0-0
        name: chi-signoz-prod-clickhouse-deploy-confd-cluster-0-0
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: signoz-prod:clickhouse.altinity.com/ClickHouseInstallation:platform/signoz-prod-clickhouse
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: clickhouse
        app.kubernetes.io/instance: signoz-prod
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: clickhouse
        app.kubernetes.io/version: 24.1.2
        clickhouse.altinity.com/app: chop
        clickhouse.altinity.com/chi: signoz-prod-clickhouse
        clickhouse.altinity.com/cluster: cluster
        clickhouse.altinity.com/namespace: platform
        clickhouse.altinity.com/replica: "0"
        clickhouse.altinity.com/shard: "0"
        helm.sh/chart: clickhouse-24.1.6
      name: data-volumeclaim-template
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Ti
      storageClassName: gp3
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: chi-signoz-prod-clickhouse-cluster-0-0-b6996dd8c
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: chi-signoz-prod-clickhouse-cluster-0-0-b6996dd8c
  updatedReplicas: 1
