apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    helm.sh/hook-weight: "3"
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: platform
  creationTimestamp: "2024-09-10T12:24:48Z"
  generation: 13
  labels:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: signoz
    app.kubernetes.io/version: 0.53.0
    helm.sh/chart: signoz-0.51.0
  name: my-release-signoz-otel-collector
  namespace: platform
  resourceVersion: "18831640"
  uid: dcb65354-bab9-41fe-ab20-45853371233e
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: otel-collector
      app.kubernetes.io/instance: my-release
      app.kubernetes.io/name: signoz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 2fd6c390880938e4b3f6024dd3aa114d8562662edda046c3bb6e4852457d46b7
        kubectl.kubernetes.io/restartedAt: "2024-09-17T09:45:31+08:00"
        signoz.io/port: "8888"
        signoz.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: otel-collector
        app.kubernetes.io/instance: my-release
        app.kubernetes.io/name: signoz
    spec:
      containers:
      - args:
        - --config=/conf/otel-collector-config.yaml
        - --manager-config=/conf/otel-collector-opamp-config.yaml
        - --copy-path=/var/tmp/collector-config.yaml
        - --feature-gates=-pkg.translator.prometheus.NormalizeName
        command:
        - /signoz-collector
        env:
        - name: CLICKHOUSE_HOST
          value: my-release-clickhouse
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: CLICKHOUSE_HTTP_PORT
          value: "8123"
        - name: CLICKHOUSE_CLUSTER
          value: cluster
        - name: CLICKHOUSE_DATABASE
          value: signoz_metrics
        - name: CLICKHOUSE_TRACE_DATABASE
          value: signoz_traces
        - name: CLICKHOUSE_LOG_DATABASE
          value: signoz_logs
        - name: CLICKHOUSE_USER
          value: admin
        - name: CLICKHOUSE_PASSWORD
          value: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
        - name: CLICKHOUSE_SECURE
          value: "false"
        - name: CLICKHOUSE_VERIFY
          value: "false"
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_CLUSTER_NAME
        - name: SIGNOZ_COMPONENT
          value: otel-collector
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: signoz.component=$(SIGNOZ_COMPONENT),k8s.cluster.name=$(K8S_CLUSTER_NAME),k8s.pod.uid=$(K8S_POD_UID),k8s.pod.ip=$(K8S_POD_IP)
        - name: LOW_CARDINAL_EXCEPTION_GROUPING
          value: "false"
        image: docker.io/signoz/signoz-otel-collector:0.102.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: collector
        ports:
        - containerPort: 14250
          name: jaeger-grpc
          protocol: TCP
        - containerPort: 14268
          name: jaeger-thrift
          protocol: TCP
        - containerPort: 8081
          name: logsheroku
          protocol: TCP
        - containerPort: 8082
          name: logsjson
          protocol: TCP
        - containerPort: 8888
          name: metrics
          protocol: TCP
        - containerPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: "1"
            memory: 2000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: otel-collector-config-vol
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - job
        - my-release-signoz-schema-migrator-upgrade
        image: docker.io/groundnuty/k8s-wait-for:v2.0
        imagePullPolicy: IfNotPresent
        name: my-release-signoz-otel-collector-migrate-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        eks.amazonaws.com/nodegroup: otel-20240911101200250200000002
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: my-release-signoz-otel-collector
      serviceAccountName: my-release-signoz-otel-collector
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: otel-collector
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          defaultMode: 420
          name: my-release-signoz-otel-collector
        name: otel-collector-config-vol
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2024-09-17T02:15:36Z"
    lastUpdateTime: "2024-09-17T02:15:57Z"
    message: ReplicaSet "my-release-signoz-otel-collector-64f445c957" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-10-12T13:29:39Z"
    lastUpdateTime: "2024-10-12T13:29:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 13
  readyReplicas: 10
  replicas: 10
  updatedReplicas: 10
