apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: signoz:apps/Deployment:platform/signoz-otel-collector
    deployment.kubernetes.io/revision: "4"
    helm.sh/hook-weight: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"signoz:apps/Deployment:platform/signoz-otel-collector","helm.sh/hook-weight":"3"},"labels":{"app.kubernetes.io/component":"otel-collector","app.kubernetes.io/instance":"signoz","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"signoz","app.kubernetes.io/version":"0.53.0","helm.sh/chart":"signoz-0.51.0"},"name":"signoz-otel-collector","namespace":"platform"},"spec":{"minReadySeconds":5,"progressDeadlineSeconds":120,"replicas":10,"selector":{"matchLabels":{"app.kubernetes.io/component":"otel-collector","app.kubernetes.io/instance":"signoz","app.kubernetes.io/name":"signoz"}},"template":{"metadata":{"annotations":{"checksum/config":"da8ffbbacfc1732e23d3b65f8124fe2abce0664face5a0d55899451c2bbefd1c","signoz.io/port":"8888","signoz.io/scrape":"true"},"labels":{"app.kubernetes.io/component":"otel-collector","app.kubernetes.io/instance":"signoz","app.kubernetes.io/name":"signoz"}},"spec":{"containers":[{"args":["--config=/conf/otel-collector-config.yaml","--manager-config=/conf/otel-collector-opamp-config.yaml","--copy-path=/var/tmp/collector-config.yaml","--feature-gates=-pkg.translator.prometheus.NormalizeName"],"command":["/signoz-collector"],"env":[{"name":"CLICKHOUSE_HOST","value":"signoz-clickhouse"},{"name":"CLICKHOUSE_PORT","value":"9000"},{"name":"CLICKHOUSE_HTTP_PORT","value":"8123"},{"name":"CLICKHOUSE_CLUSTER","value":"cluster"},{"name":"CLICKHOUSE_DATABASE","value":"signoz_metrics"},{"name":"CLICKHOUSE_TRACE_DATABASE","value":"signoz_traces"},{"name":"CLICKHOUSE_LOG_DATABASE","value":"signoz_logs"},{"name":"CLICKHOUSE_USER","value":"admin"},{"name":"CLICKHOUSE_PASSWORD","value":"27ff0399-0d3a-4bd8-919d-17c2181e6fb9"},{"name":"CLICKHOUSE_SECURE","value":"false"},{"name":"CLICKHOUSE_VERIFY","value":"false"},{"name":"K8S_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"K8S_POD_IP","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"status.podIP"}}},{"name":"K8S_HOST_IP","valueFrom":{"fieldRef":{"fieldPath":"status.hostIP"}}},{"name":"K8S_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"K8S_POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.uid"}}},{"name":"K8S_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"K8S_CLUSTER_NAME","value":null},{"name":"SIGNOZ_COMPONENT","value":"otel-collector"},{"name":"OTEL_RESOURCE_ATTRIBUTES","value":"signoz.component=$(SIGNOZ_COMPONENT),k8s.cluster.name=$(K8S_CLUSTER_NAME),k8s.pod.uid=$(K8S_POD_UID),k8s.pod.ip=$(K8S_POD_IP)"},{"name":"LOW_CARDINAL_EXCEPTION_GROUPING","value":"false"}],"image":"docker.io/signoz/signoz-otel-collector:0.102.7","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":6,"httpGet":{"path":"/","port":13133},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"collector","ports":[{"containerPort":14250,"name":"jaeger-grpc","protocol":"TCP"},{"containerPort":14268,"name":"jaeger-thrift","protocol":"TCP"},{"containerPort":8081,"name":"logsheroku","protocol":"TCP"},{"containerPort":8082,"name":"logsjson","protocol":"TCP"},{"containerPort":8888,"name":"metrics","protocol":"TCP"},{"containerPort":4317,"name":"otlp","protocol":"TCP"},{"containerPort":4318,"name":"otlp-http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":6,"httpGet":{"path":"/","port":13133},"initialDelaySeconds":5,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"requests":{"cpu":"100m","memory":"200Mi"}},"volumeMounts":[{"mountPath":"/conf","name":"otel-collector-config-vol"}]}],"initContainers":[{"args":["job","signoz-schema-migrator-init"],"image":"docker.io/groundnuty/k8s-wait-for:v2.0","imagePullPolicy":"IfNotPresent","name":"signoz-otel-collector-migrate-init"}],"priorityClassName":"","securityContext":{},"serviceAccountName":"signoz-otel-collector","topologySpreadConstraints":[{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"otel-collector"}},"maxSkew":1,"topologyKey":"kubernetes.io/hostname","whenUnsatisfiable":"ScheduleAnyway"}],"volumes":[{"configMap":{"name":"signoz-otel-collector"},"name":"otel-collector-config-vol"}]}}}}
  creationTimestamp: "2024-10-16T08:25:12Z"
  generation: 4
  labels:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: signoz
    app.kubernetes.io/version: 0.53.0
    helm.sh/chart: signoz-0.51.0
  name: signoz-otel-collector
  namespace: platform
  resourceVersion: "19495635"
  uid: 9b42bfdf-ccfb-4964-b4fe-02f93a46f836
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: otel-collector
      app.kubernetes.io/instance: signoz
      app.kubernetes.io/name: signoz
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: da8ffbbacfc1732e23d3b65f8124fe2abce0664face5a0d55899451c2bbefd1c
        kubectl.kubernetes.io/restartedAt: "2024-10-17T09:10:58+08:00"
        signoz.io/port: "8888"
        signoz.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: otel-collector
        app.kubernetes.io/instance: signoz
        app.kubernetes.io/name: signoz
    spec:
      containers:
      - args:
        - --config=/conf/otel-collector-config.yaml
        - --manager-config=/conf/otel-collector-opamp-config.yaml
        - --copy-path=/var/tmp/collector-config.yaml
        - --feature-gates=-pkg.translator.prometheus.NormalizeName
        command:
        - /signoz-collector
        env:
        - name: CLICKHOUSE_HOST
          value: signoz-clickhouse
        - name: CLICKHOUSE_PORT
          value: "9000"
        - name: CLICKHOUSE_HTTP_PORT
          value: "8123"
        - name: CLICKHOUSE_CLUSTER
          value: cluster
        - name: CLICKHOUSE_DATABASE
          value: signoz_metrics
        - name: CLICKHOUSE_TRACE_DATABASE
          value: signoz_traces
        - name: CLICKHOUSE_LOG_DATABASE
          value: signoz_logs
        - name: CLICKHOUSE_USER
          value: admin
        - name: CLICKHOUSE_PASSWORD
          value: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
        - name: CLICKHOUSE_SECURE
          value: "false"
        - name: CLICKHOUSE_VERIFY
          value: "false"
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: K8S_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: K8S_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: K8S_CLUSTER_NAME
        - name: SIGNOZ_COMPONENT
          value: otel-collector
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: signoz.component=$(SIGNOZ_COMPONENT),k8s.cluster.name=$(K8S_CLUSTER_NAME),k8s.pod.uid=$(K8S_POD_UID),k8s.pod.ip=$(K8S_POD_IP)
        - name: LOW_CARDINAL_EXCEPTION_GROUPING
          value: "false"
        image: docker.io/signoz/signoz-otel-collector:0.102.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: collector
        ports:
        - containerPort: 14250
          name: jaeger-grpc
          protocol: TCP
        - containerPort: 14268
          name: jaeger-thrift
          protocol: TCP
        - containerPort: 8081
          name: logsheroku
          protocol: TCP
        - containerPort: 8082
          name: logsjson
          protocol: TCP
        - containerPort: 8888
          name: metrics
          protocol: TCP
        - containerPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 4318
          name: otlp-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: otel-collector-config-vol
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - job
        - signoz-schema-migrator-init
        image: docker.io/groundnuty/k8s-wait-for:v2.0
        imagePullPolicy: IfNotPresent
        name: signoz-otel-collector-migrate-init
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        eks.amazonaws.com/nodegroup: otel-20240911101200250200000002
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: signoz-otel-collector
      serviceAccountName: signoz-otel-collector
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: otel-collector
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - configMap:
          defaultMode: 420
          name: signoz-otel-collector
        name: otel-collector-config-vol
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2024-10-17T03:07:45Z"
    lastUpdateTime: "2024-10-17T03:07:45Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-10-17T03:35:08Z"
    lastUpdateTime: "2024-10-17T03:35:08Z"
    message: ReplicaSet "signoz-otel-collector-6f8c965574" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 2
  replicas: 13
  unavailableReplicas: 11
  updatedReplicas: 10
