allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-09-10T03:45:01Z"
  labels:
    argocd.argoproj.io/instance: addon-in-cluster-aws-ebs-csi-resources
  name: gp3
  resourceVersion: "10440"
parameters:
  encrypted: "true"
  fsType: ext4
  type: gp3
  iops: "16000"
  throughput: "1000"
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
