apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-10-16T08:20:33Z"
  generateName: signoz-schema-migrator-init-
  labels:
    app.kubernetes.io/component: schema-migrator-init
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
    batch.kubernetes.io/controller-uid: a24206eb-8026-4cbc-ac20-de57b7dd5ab5
    batch.kubernetes.io/job-name: signoz-schema-migrator-init
    controller-uid: a24206eb-8026-4cbc-ac20-de57b7dd5ab5
    job-name: signoz-schema-migrator-init
  name: signoz-schema-migrator-init-9zxbs
  namespace: platform
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: signoz-schema-migrator-init
    uid: a24206eb-8026-4cbc-ac20-de57b7dd5ab5
  resourceVersion: "19054089"
  uid: bb0adb25-3b3e-40d2-80b9-16faac345a4f
spec:
  containers:
  - args:
    - --dsn
    - tcp://$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)@signoz-clickhouse:9000
    - --replication
    env:
    - name: CLICKHOUSE_HOST
      value: signoz-clickhouse
    - name: CLICKHOUSE_PORT
      value: "9000"
    - name: CLICKHOUSE_HTTP_PORT
      value: "8123"
    - name: CLICKHOUSE_CLUSTER
      value: cluster
    - name: CLICKHOUSE_USER
      value: admin
    - name: CLICKHOUSE_PASSWORD
      value: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
    - name: CLICKHOUSE_SECURE
      value: "false"
    image: docker.io/signoz/signoz-schema-migrator:0.102.7
    imagePullPolicy: IfNotPresent
    name: schema-migrator
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7td4x
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - command:
    - sh
    - -c
    - until wget --user "$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)" --spider -q signoz-clickhouse:8123/ping;
      do echo -e "waiting for clickhouseDB"; sleep 5; done; echo -e "clickhouse ready,
      starting schema migrator now";
    env:
    - name: CLICKHOUSE_HOST
      value: signoz-clickhouse
    - name: CLICKHOUSE_PORT
      value: "9000"
    - name: CLICKHOUSE_HTTP_PORT
      value: "8123"
    - name: CLICKHOUSE_CLUSTER
      value: cluster
    - name: CLICKHOUSE_USER
      value: admin
    - name: CLICKHOUSE_PASSWORD
      value: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
    - name: CLICKHOUSE_SECURE
      value: "false"
    image: docker.io/busybox:1.35
    imagePullPolicy: IfNotPresent
    name: signoz-schema-migrator-init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7td4x
      readOnly: true
  - command:
    - sh
    - -c
    - |
      echo "Running clickhouse ready check"
      while true
      do
        version="$(CLICKHOUSE_VERSION)"
        shards="$(CLICKHOUSE_SHARDS)"
        replicas="$(CLICKHOUSE_REPLICAS)"
        current_version="$(clickhouse client --host ${CLICKHOUSE_HOST} --port ${CLICKHOUSE_PORT} --user "${CLICKHOUSE_USER}" --password "${CLICKHOUSE_PASSWORD}" -q "SELECT version()")"
        if [ -z "$current_version" ]; then
          echo "waiting for clickhouse to be ready"
          sleep 5
          continue
        fi
        if [ -z "$(echo "$current_version" | grep "$version")" ]; then
          echo "expected version: $version, current version: $current_version"
          echo "waiting for clickhouse with correct version"
          sleep 5
          continue
        fi
        current_shards="$(clickhouse client --host ${CLICKHOUSE_HOST} --port ${CLICKHOUSE_PORT} --user "${CLICKHOUSE_USER}" --password "${CLICKHOUSE_PASSWORD}" -q "SELECT count(DISTINCT(shard_num)) FROM system.clusters WHERE cluster = '${CLICKHOUSE_CLUSTER}'")"
        if [ -z "$current_shards" ]; then
          echo "waiting for clickhouse to be ready"
          sleep 5
          continue
        fi
        if [ "$current_shards" -ne "$shards" ]; then
          echo "expected shard count: $shards, current shard count: $current_shards"
          echo "waiting for clickhouse with correct shard count"
          sleep 5
          continue
        fi
        current_replicas="$(clickhouse client --host ${CLICKHOUSE_HOST} --port ${CLICKHOUSE_PORT} --user "${CLICKHOUSE_USER}" --password "${CLICKHOUSE_PASSWORD}" -q "SELECT count(DISTINCT(replica_num)) FROM system.clusters WHERE cluster = '${CLICKHOUSE_CLUSTER}'")"
        if [ -z "$current_replicas" ]; then
          echo "waiting for clickhouse to be ready"
          sleep 5
          continue
        fi
        if [ "$current_replicas" -ne "$replicas" ]; then
          echo "expected replica count: $replicas, current replica count: $current_replicas"
          echo "waiting for clickhouse with correct replica count"
          sleep 5
          continue
        fi
        break
      done
      echo "clickhouse ready, starting schema migrator now"
    env:
    - name: CLICKHOUSE_HOST
      value: signoz-clickhouse
    - name: CLICKHOUSE_PORT
      value: "9000"
    - name: CLICKHOUSE_HTTP_PORT
      value: "8123"
    - name: CLICKHOUSE_CLUSTER
      value: cluster
    - name: CLICKHOUSE_USER
      value: admin
    - name: CLICKHOUSE_PASSWORD
      value: 27ff0399-0d3a-4bd8-919d-17c2181e6fb9
    - name: CLICKHOUSE_SECURE
      value: "false"
    - name: CLICKHOUSE_VERSION
      value: 24.1.2
    - name: CLICKHOUSE_SHARDS
      value: "6"
    - name: CLICKHOUSE_REPLICAS
      value: "2"
    image: docker.io/clickhouse/clickhouse-server:24.1.2-alpine
    imagePullPolicy: IfNotPresent
    name: signoz-schema-migrator-ch-ready
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7td4x
      readOnly: true
  nodeName: ip-10-150-43-86.ap-southeast-1.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7td4x
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-16T08:36:30Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-10-16T08:24:06Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-16T08:36:29Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-16T08:36:29Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-16T08:20:33Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://c0359de102118587a1d477097f62d40818c7ee244c1a62bd43ee3c35285cd715
    image: docker.io/signoz/signoz-schema-migrator:0.102.7
    imageID: docker.io/signoz/signoz-schema-migrator@sha256:fd6599f311950963bca9a47f2df1bcf28ef90375f8c3eca208860436d50dc45c
    lastState: {}
    name: schema-migrator
    ready: false
    restartCount: 5
    started: false
    state:
      terminated:
        containerID: containerd://c0359de102118587a1d477097f62d40818c7ee244c1a62bd43ee3c35285cd715
        exitCode: 0
        finishedAt: "2024-10-16T08:36:29Z"
        reason: Completed
        startedAt: "2024-10-16T08:35:54Z"
  hostIP: 10.150.43.86
  hostIPs:
  - ip: 10.150.43.86
  initContainerStatuses:
  - containerID: containerd://9aa7e4860b673935929df71ff0aed7b6ab321b00059bc66d04f10368dcde27ce
    image: docker.io/library/busybox:1.35
    imageID: docker.io/library/busybox@sha256:c35c2d1935d7771a5ada493a2207afa3fbad90a750e9ded24a449fdb134137a4
    lastState: {}
    name: signoz-schema-migrator-init
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://9aa7e4860b673935929df71ff0aed7b6ab321b00059bc66d04f10368dcde27ce
        exitCode: 0
        finishedAt: "2024-10-16T08:24:04Z"
        reason: Completed
        startedAt: "2024-10-16T08:20:34Z"
  - containerID: containerd://dcad2b926bb5180d669e34e2c182679fb108ac348cfce8eb7b200776e5f80371
    image: docker.io/clickhouse/clickhouse-server:24.1.2-alpine
    imageID: docker.io/clickhouse/clickhouse-server@sha256:1db999ade4b8c16397c42a3818881eba7e8a35369ce53e6374bf9cf498d87d28
    lastState: {}
    name: signoz-schema-migrator-ch-ready
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://dcad2b926bb5180d669e34e2c182679fb108ac348cfce8eb7b200776e5f80371
        exitCode: 0
        finishedAt: "2024-10-16T08:24:06Z"
        reason: Completed
        startedAt: "2024-10-16T08:24:05Z"
  phase: Succeeded
  podIP: 10.150.45.20
  podIPs:
  - ip: 10.150.45.20
  qosClass: BestEffort
  startTime: "2024-10-16T08:20:33Z"
