apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"alb.ingress.kubernetes.io/scheme":"internet-facing","meta.helm.sh/release-name":"signoz","meta.helm.sh/release-namespace":"platform"},"finalizers":["service.kubernetes.io/load-balancer-cleanup"],"labels":{"app.kubernetes.io/component":"clickhouse","app.kubernetes.io/instance":"signoz","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"clickhouse","app.kubernetes.io/version":"24.1.2","clickhouse.altinity.com/Service":"chi","clickhouse.altinity.com/app":"chop","clickhouse.altinity.com/chi":"signoz-clickhouse","clickhouse.altinity.com/namespace":"platform","helm.sh/chart":"clickhouse-24.1.6"},"name":"signoz-clickhouse","namespace":"platform"},"spec":{"allocateLoadBalancerNodePorts":true,"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilyPolicy":"SingleStack","ports":[{"name":"http","port":8123,"protocol":"TCP","targetPort":8123},{"name":"tcp","port":9000,"protocol":"TCP","targetPort":9000}],"selector":{"clickhouse.altinity.com/app":"chop","clickhouse.altinity.com/chi":"signoz-clickhouse","clickhouse.altinity.com/namespace":"platform","clickhouse.altinity.com/ready":"yes"},"sessionAffinity":"None","type":"LoadBalancer"}}
    meta.helm.sh/release-name: signoz
    meta.helm.sh/release-namespace: platform
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 24.1.2
    clickhouse.altinity.com/Service: chi
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/namespace: platform
    helm.sh/chart: clickhouse-24.1.6
  name: signoz-clickhouse
  namespace: platform
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: signoz-clickhouse
    clickhouse.altinity.com/namespace: platform
    clickhouse.altinity.com/ready: "yes"
  sessionAffinity: None
  type: ClusterIP
