apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-release
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: my-release
      finalizers:
        # This finalizer is for demo purposes, in production remove apps using argocd CLI "argocd app delete workload --cascade"
        # When you invoke argocd app delete with --cascade, the finalizer is added automatically.
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/ranmaoshu1/datastar.git'
          path: './signoz-dev'
          directory:
            recurse: true
          targetRevision: 'HEAD'
          helm:
            valueFiles:
              - values.yaml

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'platform'
      syncPolicy:
        automated:
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 60
