apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  labels:
    app: zookeeper
  name: zookeeper-internet
  namespace: clickhouse
spec:
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
    what: node
  sessionAffinity: None
  type: LoadBalancer

