apiVersion: v1
kind: Service
metadata:
  name: ck-internet
  namespace: ch228
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  labels:
    clickhouse.altinity.com/Service: chi
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: ch228-clickhouse
    clickhouse.altinity.com/namespace: ch228
spec:
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: http
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: tcp
  selector:
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: ch228
    clickhouse.altinity.com/cluster: ch228
    clickhouse.altinity.com/namespace: ch228
    clickhouse.altinity.com/ready: "yes"
  sessionAffinity: None
  type: LoadBalancer
